//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apothecary
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Combo
    {
        public int EssentialOilId1 { get; set; }
        public int EssentialOilId2 { get; set; }
    
        public virtual EssentialOil EssentialOil1 { get; set; }
        public virtual EssentialOil EssentialOil2 { get; set; }
    }
}
